### ISSUE TITLE
error when running test file pool.test.ts

### ISSUE THREAD

**Issue by nlakhoa** [CetusProtocol/cetus-clmm-sui-sdk#20]
when I run test('doCreatPools') the following error occurs:
    error:  Error: Dry run failed, could not automatically determine a budget: MoveAbort(MoveLocation { module: ModuleId { address: 0c7ae833c220aa73a3643a0d508afa4ac5d50d97312ea4584e35f9eb21b9df12, name: Identifier("config") }, function: 15, instruction: 8, function_name: Some("check_pool_manager_role") }, 5) in command 0
        at setGasBudget (/Users/anhkhoa/asdi/bot/research/cetus-clmm-sui-sdk/node_modules/@mysten/sui/src/transactions/json-rpc-resolver.ts:84:9)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at resolveTransactionData (/Users/anhkhoa/asdi/bot/research/cetus-clmm-sui-sdk/node_modules/@mysten/sui/src/transactions/json-rpc-resolver.ts:48:3)
        at /Users/anhkhoa/asdi/bot/research/cetus-clmm-sui-sdk/node_modules/@mysten/sui/src/transactions/Transaction.ts:585:5
        at _Transaction.runPlugins_fn (/Users/anhkhoa/asdi/bot/research/cetus-clmm-sui-sdk/node_modules/@mysten/sui/src/transactions/Transaction.ts:607:3)
        at _Transaction.prepareBuild_fn (/Users/anhkhoa/asdi/bot/research/cetus-clmm-sui-sdk/node_modules/@mysten/sui/src/transactions/Transaction.ts:570:3)
        at _Transaction.build (/Users/anhkhoa/asdi/bot/research/cetus-clmm-sui-sdk/node_modules/@mysten/sui/src/transactions/Transaction.ts:545:3)
        at RpcModule.signAndExecuteTransaction (/Users/anhkhoa/asdi/bot/research/cetus-clmm-sui-sdk/node_modules/@mysten/sui/src/client/client.ts:454:23)
        at RpcModule.sendTransaction (/Users/anhkhoa/asdi/bot/research/cetus-clmm-sui-sdk/src/modules/rpcModule.ts:179:30)
        at Object.<anonymous> (/Users/anhkhoa/asdi/bot/research/cetus-clmm-sui-sdk/tests/pool.test.ts:53:25) {
      [cause]: {
        effects: {
          messageVersion: 'v1',
          status: [Object],
          executedEpoch: '564',
          gasUsed: [Object],
          modifiedAtVersions: [Array],
          sharedObjects: [Array],
          transactionDigest: 'AB4HRzzjRuUMzHGTdpBZUSpaDrFf3phkZsTeuq1SnZx3',
          mutated: [Array],
          gasObject: [Object],
          dependencies: [Array]
        },
        events: [],
        objectChanges: [ [Object], [Object] ],
        balanceChanges: [ [Object] ],
        input: {
          messageVersion: 'v1',
          transaction: [Object],
          sender: '0x2a6174f94a2c1d648de290297be27867527a6aaa263a4e0a567c9cd7656d3651',
          gasData: [Object]
        }
      }
    }. Please help me fix this error

**Comment by nlakhoa** [comment]
Why did you kick me out of the Discord channel?

**Comment by nlakhoa** [comment]
I need help creating a pool using the SDK https://www.npmjs.com/package/@cetusprotocol/cetus-sui-clmm-sdk, but you just told me to read the docs even though your docs and the SDK don’t match. I wasn’t getting support in the ticket, so I went to the general group to ask for help, but then you kicked me. Why?

**Comment by martins-ojakominor** [comment]
> I need help creating a pool using the SDK https://www.npmjs.com/package/@cetusprotocol/cetus-sui-clmm-sdk, but you just told me to read the docs even though your docs and the SDK don’t match. I wasn’t getting support in the ticket, so I went to the general group to ask for help, but then you kicked me. Why?

Same here. they seem to be very clueless on their discord support. I wonder why they would have an SDK with a different documentation. makes me want to go crazy.

**Comment by nlakhoa** [comment]
> > I need help creating a pool using the SDK https://www.npmjs.com/package/@cetusprotocol/cetus-sui-clmm-sdk, but you just told me to read the docs even though your docs and the SDK don’t match. I wasn’t getting support in the ticket, so I went to the general group to ask for help, but then you kicked me. Why?
> 
> Same here. they seem to be very clueless on their discord support. I wonder why they would have an SDK with a different documentation. makes me want to go crazy.

maybe they don't want us to understand
